{{- if and (not .Values.existingSecretName) .Values.secretEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-books.fullname" . }}
  labels:
    {{- include "simple-books.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
